<?php
declare(strict_types=1);

namespace PhpAsm\Codegen;

use PhpAsm\IR\ArrayAccessExpr;
use PhpAsm\IR\ArrayLiteralExpr;
use PhpAsm\IR\AssignStmt;
use PhpAsm\IR\BinaryExpr;
use PhpAsm\IR\CallExpr;
use PhpAsm\IR\Expr;
use PhpAsm\IR\ExprStmt;
use PhpAsm\IR\FloatExpr;
use PhpAsm\IR\ForStmt;
use PhpAsm\IR\FunctionDef;
use PhpAsm\IR\IfStmt;
use PhpAsm\IR\ImportFunc;
use PhpAsm\IR\IntExpr;
use PhpAsm\IR\Program;
use PhpAsm\IR\ReturnStmt;
use PhpAsm\IR\Stmt;
use PhpAsm\IR\StringExpr;
use PhpAsm\IR\VarExpr;
use PhpAsm\IR\WhileStmt;
use RuntimeException;

final class FasmGenerator
{
    /**
     * @var array<string, string>
     */
    private array $stringPool = [];

    /**
     * @var list<array{name: string, bytes: list<int>}>
     */
    private array $stringData = [];

    /**
     * @var list<array{name: string, kind: string, values: list<int|string>}>
     */
    private array $arrayData = [];

    private int $stringCounter = 0;
    private int $arrayCounter = 0;

    /**
     * @var array<string, string>
     */
    private array $globalTypes = [];

    /**
     * @var array<string, string>
     */
    private array $globalLabels = [];

    /**
     * @var array<string, ImportFunc>
     */
    private array $importsByName = [];

    public function generate(Program $program): string
    {
        foreach ($program->imports as $imp) {
            $this->importsByName[$imp->localName] = $imp;
        }

        foreach ($program->globals as $g) {
            $this->globalTypes[$g->name] = $g->type;
            $label = 'g_' . count($this->globalLabels);
            $this->globalLabels[$g->name] = $label;

            if ($g->initializer instanceof IntExpr) {
                $this->arrayData[] = ['name' => $label, 'kind' => 'dd_int', 'values' => [$g->initializer->value]];
                continue;
            }
            if ($g->initializer instanceof FloatExpr) {
                $this->arrayData[] = ['name' => $label, 'kind' => 'dd_hex', 'values' => [$this->floatToBits($g->initializer->value)]];
                continue;
            }
            if ($g->initializer instanceof StringExpr) {
                $str = $this->internString($g->initializer->value);
                $this->arrayData[] = ['name' => $label, 'kind' => 'dd_label', 'values' => [$str]];
                continue;
            }
            if ($g->initializer instanceof ArrayLiteralExpr) {
                $arrLabel = $this->internArrayLiteral($g->initializer);
                $this->arrayData[] = ['name' => $label, 'kind' => 'dd_label', 'values' => [$arrLabel]];
                continue;
            }
            throw new RuntimeException("Unsupported global initializer.");
        }

        $asm = [];
        $asm[] = '; Generated by phpasm';
        $asm[] = 'format PE console 4.0';
        $asm[] = 'entry start';
        $asm[] = '';
        $asm[] = "include 'win32a.inc'";
        $asm[] = '';
        $asm[] = "section '.text' code readable executable";
        $asm[] = 'start:';
        $asm[] = '    call fn_main';
        $asm[] = '    invoke ExitProcess, eax';
        $asm[] = '';

        foreach ($program->functions as $fn) {
            foreach ($this->renderFunction($fn) as $line) {
                $asm[] = $line;
            }
            $asm[] = '';
        }

        $asm[] = "section '.data' data readable writeable";
        foreach ($this->stringData as $str) {
            $asm[] = "{$str['name']} db " . implode(', ', $str['bytes']);
        }
        foreach ($this->arrayData as $arr) {
            if ($arr['kind'] === 'dd_int') {
                $asm[] = "{$arr['name']} dd " . implode(', ', array_map(static fn($v): string => (string)$v, $arr['values']));
            } elseif ($arr['kind'] === 'dd_hex') {
                $asm[] = "{$arr['name']} dd " . implode(', ', array_map(static fn($v): string => '0x' . strtoupper((string)$v), $arr['values']));
            } else {
                $asm[] = "{$arr['name']} dd " . implode(', ', array_map(static fn($v): string => (string)$v, $arr['values']));
            }
        }

        $asm[] = '';
        $asm[] = "section '.idata' import data readable writeable";
        $libraries = ['kernel32' => 'KERNEL32.DLL'];
        if ($program->usesPrintf) {
            $libraries['msvcrt'] = 'msvcrt.dll';
        }
        if ($program->usesHeap) {
            $libraries['kernel32'] = 'KERNEL32.DLL';
        }
        foreach ($program->imports as $imp) {
            $alias = $this->dllAlias($imp->dll);
            $libraries[$alias] = $imp->dll;
        }

        $libraryParts = [];
        foreach ($libraries as $alias => $dll) {
            $libraryParts[] = "{$alias}, '{$dll}'";
        }
        $asm[] = "library " . implode(', ', $libraryParts);

        $imports = [];
        $imports['kernel32'] = ["ExitProcess, 'ExitProcess'"];
        if ($program->usesHeap) {
            $imports['kernel32'][] = "GetProcessHeap, 'GetProcessHeap'";
            $imports['kernel32'][] = "HeapAlloc, 'HeapAlloc'";
            $imports['kernel32'][] = "HeapFree, 'HeapFree'";
        }
        if ($program->usesPrintf) {
            $imports['msvcrt'] = ["printf, 'printf'"];
        }
        foreach ($program->imports as $imp) {
            $alias = $this->dllAlias($imp->dll);
            $imports[$alias] ??= [];
            $imports[$alias][] = "{$imp->localName}, '{$imp->symbol}'";
        }
        foreach ($imports as $alias => $items) {
            $asm[] = "import {$alias}, " . implode(', ', $items);
        }
        $asm[] = '';

        return implode("\n", $asm);
    }

    /**
     * @return list<string>
     */
    private function renderFunction(FunctionDef $fn): array
    {
        $ctx = new FunctionContext($fn, $this->globalLabels);
        $this->collectLocals($fn->body, $ctx);

        $lines = [];
        $lines[] = "fn_{$fn->name}:";
        $lines[] = '    push ebp';
        $lines[] = '    mov ebp, esp';
        $stack = $ctx->computeStackSize();
        if ($stack > 0) {
            $lines[] = "    sub esp, {$stack}";
        }
        foreach ($fn->body as $stmt) {
            $lines = array_merge($lines, $this->renderStmt($stmt, $ctx));
        }
        if ($fn->returnType === 'void') {
            $lines[] = '    mov eax, 0';
        }
        $lines[] = "ret_{$fn->name}:";
        $lines[] = '    mov esp, ebp';
        $lines[] = '    pop ebp';
        $lines[] = '    ret';
        return $lines;
    }

    /**
     * @param list<Stmt> $stmts
     */
    private function collectLocals(array $stmts, FunctionContext $ctx): void
    {
        foreach ($stmts as $stmt) {
            if ($stmt instanceof AssignStmt) {
                $ctx->declareLocal($stmt->varName);
                continue;
            }
            if ($stmt instanceof IfStmt || $stmt instanceof WhileStmt) {
                $this->collectLocals($stmt->body, $ctx);
                continue;
            }
            if ($stmt instanceof ForStmt) {
                if ($stmt->init instanceof AssignStmt) {
                    $ctx->declareLocal($stmt->init->varName);
                }
                if ($stmt->post instanceof AssignStmt) {
                    $ctx->declareLocal($stmt->post->varName);
                }
                $this->collectLocals($stmt->body, $ctx);
            }
        }
    }

    /**
     * @return list<string>
     */
    private function renderStmt(Stmt $stmt, FunctionContext $ctx): array
    {
        if ($stmt instanceof AssignStmt) {
            $lines = $this->renderExpr($stmt->expr, $ctx);
            $lines[] = '    mov ' . $ctx->memForVar($stmt->varName) . ', eax';
            return $lines;
        }
        if ($stmt instanceof ReturnStmt) {
            if ($stmt->expr === null) {
                return ["    jmp ret_{$ctx->fn->name}"];
            }
            $lines = $this->renderExpr($stmt->expr, $ctx);
            $lines[] = "    jmp ret_{$ctx->fn->name}";
            return $lines;
        }
        if ($stmt instanceof ExprStmt) {
            return $this->renderExpr($stmt->expr, $ctx);
        }
        if ($stmt instanceof IfStmt) {
            $end = $ctx->newLabel('if_end');
            $lines = $this->renderExpr($stmt->condition, $ctx);
            $lines[] = '    cmp eax, 0';
            $lines[] = "    je {$end}";
            foreach ($stmt->body as $child) {
                $lines = array_merge($lines, $this->renderStmt($child, $ctx));
            }
            $lines[] = "{$end}:";
            return $lines;
        }
        if ($stmt instanceof WhileStmt) {
            $start = $ctx->newLabel('while_start');
            $end = $ctx->newLabel('while_end');
            $lines = ["{$start}:"];
            $lines = array_merge($lines, $this->renderExpr($stmt->condition, $ctx));
            $lines[] = '    cmp eax, 0';
            $lines[] = "    je {$end}";
            foreach ($stmt->body as $child) {
                $lines = array_merge($lines, $this->renderStmt($child, $ctx));
            }
            $lines[] = "    jmp {$start}";
            $lines[] = "{$end}:";
            return $lines;
        }
        if ($stmt instanceof ForStmt) {
            $start = $ctx->newLabel('for_start');
            $end = $ctx->newLabel('for_end');
            $lines = [];
            if ($stmt->init !== null) {
                $lines = array_merge($lines, $this->renderStmt($stmt->init, $ctx));
            }
            $lines[] = "{$start}:";
            if ($stmt->condition !== null) {
                $lines = array_merge($lines, $this->renderExpr($stmt->condition, $ctx));
                $lines[] = '    cmp eax, 0';
                $lines[] = "    je {$end}";
            }
            foreach ($stmt->body as $child) {
                $lines = array_merge($lines, $this->renderStmt($child, $ctx));
            }
            if ($stmt->post !== null) {
                $lines = array_merge($lines, $this->renderStmt($stmt->post, $ctx));
            }
            $lines[] = "    jmp {$start}";
            $lines[] = "{$end}:";
            return $lines;
        }
        throw new RuntimeException('Unsupported statement.');
    }

    /**
     * @return list<string>
     */
    private function renderExpr(Expr $expr, FunctionContext $ctx): array
    {
        if ($expr instanceof IntExpr) {
            return ["    mov eax, {$expr->value}"];
        }
        if ($expr instanceof FloatExpr) {
            return ["    mov eax, 0x" . $this->floatToBits($expr->value)];
        }
        if ($expr instanceof StringExpr) {
            return ["    mov eax, " . $this->internString($expr->value)];
        }
        if ($expr instanceof ArrayLiteralExpr) {
            return ["    mov eax, " . $this->internArrayLiteral($expr)];
        }
        if ($expr instanceof VarExpr) {
            return ["    mov eax, " . $ctx->memForVar($expr->name)];
        }
        if ($expr instanceof ArrayAccessExpr) {
            $lines = $this->renderExpr($expr->arrayExpr, $ctx);
            $lines[] = '    push eax';
            $lines = array_merge($lines, $this->renderExpr($expr->indexExpr, $ctx));
            $lines[] = '    mov ebx, eax';
            $lines[] = '    pop eax';
            $lines[] = '    mov eax, [eax + ebx*4]';
            return $lines;
        }
        if ($expr instanceof BinaryExpr) {
            $lines = $this->renderExpr($expr->left, $ctx);
            $lines[] = '    push eax';
            $lines = array_merge($lines, $this->renderExpr($expr->right, $ctx));
            $lines[] = '    mov ebx, eax';
            $lines[] = '    pop eax';
            return array_merge($lines, $this->emitBinaryOp($expr->op));
        }
        if ($expr instanceof CallExpr) {
            if ($expr->name === '__intrinsic_typed') {
                return $this->renderExpr($expr->args[0], $ctx);
            }

            if ($expr->name === 'printf') {
                $lines = [];
                $argBytes = 0;
                for ($i = count($expr->args) - 1; $i >= 0; $i--) {
                    $arg = $expr->args[$i];
                    $lines = array_merge($lines, $this->renderExpr($arg, $ctx));
                    if ($arg->type === 'float') {
                        $tmp = $ctx->floatTmpOffset();
                        $lines[] = "    mov [ebp-{$tmp}], eax";
                        $lines[] = "    fld dword [ebp-{$tmp}]";
                        $lines[] = '    sub esp, 8';
                        $lines[] = '    fstp qword [esp]';
                        $argBytes += 8;
                    } else {
                        $lines[] = '    push eax';
                        $argBytes += 4;
                    }
                }
                $lines[] = '    call [printf]';
                if ($argBytes > 0) {
                    $lines[] = "    add esp, {$argBytes}";
                }
                return $lines;
            }

            if ($expr->name === '__intrinsic_heap_alloc' || $expr->name === 'heap_alloc') {
                $lines = $this->renderExpr($expr->args[0], $ctx);
                $lines[] = '    mov ecx, eax';
                $lines[] = '    add eax, 4';
                $lines[] = '    push ecx';
                $lines[] = '    push eax';
                $lines[] = '    call [GetProcessHeap]';
                $lines[] = '    mov ebx, eax';
                $lines[] = '    pop eax';
                $lines[] = '    push eax';
                $lines[] = '    push 0';
                $lines[] = '    push ebx';
                $lines[] = '    call [HeapAlloc]';
                $lines[] = '    pop ecx';
                $ok = $ctx->newLabel('heap_alloc_ok');
                $lines[] = '    cmp eax, 0';
                $lines[] = "    je {$ok}";
                $lines[] = '    mov [eax], ecx';
                $lines[] = '    add eax, 4';
                $lines[] = "{$ok}:";
                return $lines;
            }

            if ($expr->name === '__intrinsic_heap_alloc_t' || preg_match('/^heap_alloc_t<(.+)>$/', $expr->name) === 1) {
                $elemSize = $this->pointerElementSize($expr->type);
                $lines = $this->renderExpr($expr->args[0], $ctx);
                $lines[] = "    imul eax, {$elemSize}";
                $lines[] = '    mov ecx, eax';
                $lines[] = '    add eax, 4';
                $lines[] = '    push ecx';
                $lines[] = '    push eax';
                $lines[] = '    call [GetProcessHeap]';
                $lines[] = '    mov ebx, eax';
                $lines[] = '    pop eax';
                $lines[] = '    push eax';
                $lines[] = '    push 0';
                $lines[] = '    push ebx';
                $lines[] = '    call [HeapAlloc]';
                $lines[] = '    pop ecx';
                $ok = $ctx->newLabel('heap_alloc_t_ok');
                $lines[] = '    cmp eax, 0';
                $lines[] = "    je {$ok}";
                $lines[] = '    mov [eax], ecx';
                $lines[] = '    add eax, 4';
                $lines[] = "{$ok}:";
                return $lines;
            }

            if ($expr->name === '__intrinsic_heap_free' || $expr->name === 'heap_free') {
                $lines = $this->renderExpr($expr->args[0], $ctx);
                $null = $ctx->newLabel('heap_free_null');
                $end = $ctx->newLabel('heap_free_end');
                $lines[] = '    cmp eax, 0';
                $lines[] = "    je {$null}";
                $lines[] = '    sub eax, 4';
                $lines[] = '    push eax';
                $lines[] = '    call [GetProcessHeap]';
                $lines[] = '    mov ebx, eax';
                $lines[] = '    pop eax';
                $lines[] = '    push eax';
                $lines[] = '    push 0';
                $lines[] = '    push ebx';
                $lines[] = '    call [HeapFree]';
                $lines[] = "    jmp {$end}";
                $lines[] = "{$null}:";
                $lines[] = '    mov eax, 1';
                $lines[] = "{$end}:";
                return $lines;
            }

            if ($expr->name === '__intrinsic_ptr_get' || $expr->name === 'ptr_get') {
                $elemSize = $this->pointerElementSize($expr->args[0]->type);
                $oob = $ctx->newLabel('ptr_get_oob');
                $done = $ctx->newLabel('ptr_get_done');
                $lines = $this->renderExpr($expr->args[0], $ctx);
                $lines[] = '    push eax';
                $lines = array_merge($lines, $this->renderExpr($expr->args[1], $ctx));
                $lines[] = '    mov ebx, eax';
                $lines[] = '    pop eax';
                $lines[] = '    cmp eax, 0';
                $lines[] = "    je {$oob}";
                $lines[] = '    cmp ebx, 0';
                $lines[] = "    jl {$oob}";
                $lines[] = '    mov ecx, [eax-4]';
                $lines[] = "    shr ecx, {$this->shiftForSize($elemSize)}";
                $lines[] = '    cmp ebx, ecx';
                $lines[] = "    jae {$oob}";
                $lines[] = "    mov eax, [eax + ebx*{$elemSize}]";
                $lines[] = "    jmp {$done}";
                $lines[] = "{$oob}:";
                $lines[] = '    mov eax, 0';
                $lines[] = "{$done}:";
                return $lines;
            }

            if ($expr->name === '__intrinsic_ptr_set' || $expr->name === 'ptr_set') {
                $elemSize = $this->pointerElementSize($expr->args[0]->type);
                $oob = $ctx->newLabel('ptr_set_oob');
                $done = $ctx->newLabel('ptr_set_done');
                $lines = $this->renderExpr($expr->args[0], $ctx);
                $lines[] = '    push eax';
                $lines = array_merge($lines, $this->renderExpr($expr->args[1], $ctx));
                $lines[] = '    push eax';
                $lines = array_merge($lines, $this->renderExpr($expr->args[2], $ctx));
                $lines[] = '    mov ecx, eax';
                $lines[] = '    pop ebx';
                $lines[] = '    pop eax';
                $lines[] = '    cmp eax, 0';
                $lines[] = "    je {$oob}";
                $lines[] = '    cmp ebx, 0';
                $lines[] = "    jl {$oob}";
                $lines[] = '    mov edx, [eax-4]';
                $lines[] = "    shr edx, {$this->shiftForSize($elemSize)}";
                $lines[] = '    cmp ebx, edx';
                $lines[] = "    jae {$oob}";
                $lines[] = "    mov [eax + ebx*{$elemSize}], ecx";
                $lines[] = '    mov eax, ecx';
                $lines[] = "    jmp {$done}";
                $lines[] = "{$oob}:";
                $lines[] = '    mov eax, 0';
                $lines[] = "{$done}:";
                return $lines;
            }

            if (isset($this->importsByName[$expr->name])) {
                $imp = $this->importsByName[$expr->name];
                $lines = [];
                $argBytes = 0;
                for ($i = count($expr->args) - 1; $i >= 0; $i--) {
                    $lines = array_merge($lines, $this->renderExpr($expr->args[$i], $ctx));
                    $lines[] = '    push eax';
                    $argBytes += 4;
                }
                $lines[] = "    call [{$imp->localName}]";
                if ($imp->convention === 'cdecl' && $argBytes > 0) {
                    $lines[] = "    add esp, {$argBytes}";
                }
                return $lines;
            }

            $lines = [];
            $argBytes = 0;
            for ($i = count($expr->args) - 1; $i >= 0; $i--) {
                $lines = array_merge($lines, $this->renderExpr($expr->args[$i], $ctx));
                $lines[] = '    push eax';
                $argBytes += 4;
            }
            $lines[] = "    call fn_{$expr->name}";
            if ($argBytes > 0) {
                $lines[] = "    add esp, {$argBytes}";
            }
            return $lines;
        }
        throw new RuntimeException('Unsupported expression.');
    }

    /**
     * @return list<string>
     */
    private function emitBinaryOp(string $op): array
    {
        return match ($op) {
            '+' => ['    add eax, ebx'],
            '-' => ['    sub eax, ebx'],
            '*' => ['    imul eax, ebx'],
            '/' => ['    cdq', '    idiv ebx'],
            '==' => ['    cmp eax, ebx', '    sete al', '    movzx eax, al'],
            '!=' => ['    cmp eax, ebx', '    setne al', '    movzx eax, al'],
            '<' => ['    cmp eax, ebx', '    setl al', '    movzx eax, al'],
            '<=' => ['    cmp eax, ebx', '    setle al', '    movzx eax, al'],
            '>' => ['    cmp eax, ebx', '    setg al', '    movzx eax, al'],
            '>=' => ['    cmp eax, ebx', '    setge al', '    movzx eax, al'],
            default => throw new RuntimeException("Unsupported operator {$op}"),
        };
    }

    private function internString(string $value): string
    {
        if (isset($this->stringPool[$value])) {
            return $this->stringPool[$value];
        }
        $label = 'str_' . $this->stringCounter++;
        $bytes = [];
        for ($i = 0, $n = strlen($value); $i < $n; $i++) {
            $bytes[] = ord($value[$i]);
        }
        $bytes[] = 0;
        $this->stringPool[$value] = $label;
        $this->stringData[] = ['name' => $label, 'bytes' => $bytes];
        return $label;
    }

    private function internArrayLiteral(ArrayLiteralExpr $arr): string
    {
        $label = 'arr_' . $this->arrayCounter++;
        if ($arr->elementType === 'int') {
            $vals = [];
            foreach ($arr->elements as $e) {
                $vals[] = $e instanceof IntExpr ? $e->value : 0;
            }
            $this->arrayData[] = ['name' => $label, 'kind' => 'dd_int', 'values' => $vals];
            return $label;
        }
        if ($arr->elementType === 'float') {
            $vals = [];
            foreach ($arr->elements as $e) {
                $vals[] = $e instanceof FloatExpr ? $this->floatToBits($e->value) : '00000000';
            }
            $this->arrayData[] = ['name' => $label, 'kind' => 'dd_hex', 'values' => $vals];
            return $label;
        }
        $vals = [];
        foreach ($arr->elements as $e) {
            $vals[] = $e instanceof StringExpr ? $this->internString($e->value) : $this->internString('');
        }
        $this->arrayData[] = ['name' => $label, 'kind' => 'dd_label', 'values' => $vals];
        return $label;
    }

    private function floatToBits(float $value): string
    {
        $arr = unpack('V', pack('f', $value));
        if (!is_array($arr) || !isset($arr[1])) {
            throw new RuntimeException('Failed to encode float.');
        }
        return str_pad(strtoupper(dechex((int)$arr[1])), 8, '0', STR_PAD_LEFT);
    }

    private function pointerElementSize(string $ptrType): int
    {
        $t = strtolower(trim($ptrType));
        if (str_starts_with($t, 'hptr<') || str_starts_with($t, 'ptr<')) {
            return 4;
        }
        return match ($t) {
            'int', 'float', 'string' => 4,
            default => throw new RuntimeException("Unsupported pointer element type: {$ptrType}"),
        };
    }

    private function shiftForSize(int $size): int
    {
        return match ($size) {
            1 => 0,
            2 => 1,
            4 => 2,
            8 => 3,
            default => throw new RuntimeException("Unsupported element size: {$size}"),
        };
    }

    private function dllAlias(string $dll): string
    {
        $base = strtolower(pathinfo($dll, PATHINFO_FILENAME));
        $base = preg_replace('/[^a-z0-9_]/', '_', $base) ?? 'lib';
        if ($base === '' || is_numeric($base[0])) {
            $base = 'lib_' . $base;
        }
        return $base;
    }
}

final class FunctionContext
{
    /**
     * @var array<string, int>
     */
    private array $locals = [];

    /**
     * @var array<string, int>
     */
    private array $params = [];

    private int $nextOffset = 0;
    private int $labelCounter = 0;
    private int $floatTmp = 0;

    /**
     * @param array<string, string> $globalLabels
     */
    public function __construct(
        public FunctionDef $fn,
        private array $globalLabels
    ) {
        $off = 8;
        foreach ($fn->params as $p) {
            $this->params[$p['name']] = $off;
            $off += 4;
        }
    }

    public function declareLocal(string $name): void
    {
        if (isset($this->locals[$name]) || isset($this->params[$name])) {
            return;
        }
        $this->nextOffset += 4;
        $this->locals[$name] = $this->nextOffset;
    }

    public function memForVar(string $name): string
    {
        if (isset($this->locals[$name])) {
            return "[ebp-{$this->locals[$name]}]";
        }
        if (isset($this->params[$name])) {
            return "[ebp+{$this->params[$name]}]";
        }
        if (isset($this->globalLabels[$name])) {
            return '[' . $this->globalLabels[$name] . ']';
        }
        throw new RuntimeException("Unknown variable: \${$name}");
    }

    public function computeStackSize(): int
    {
        if ($this->floatTmp === 0) {
            $this->nextOffset += 4;
            $this->floatTmp = $this->nextOffset;
        }
        return max(16, (int)(ceil($this->nextOffset / 16) * 16));
    }

    public function floatTmpOffset(): int
    {
        if ($this->floatTmp === 0) {
            $this->nextOffset += 4;
            $this->floatTmp = $this->nextOffset;
        }
        return $this->floatTmp;
    }

    public function newLabel(string $prefix): string
    {
        $label = 'fn_' . $this->fn->name . '_' . $prefix . '_' . $this->labelCounter;
        $this->labelCounter++;
        return $label;
    }
}
